import { UserProvider } from '@auth0/nextjs-auth0/client';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import clsx from 'clsx';

const maax = localFont({
    src: [
        {
            path: '../public/fonts/Maax-Medium-205TF.woff2',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../public/fonts/Maax-Regular-205TF.woff2',
            weight: '400',
            style: 'normal',
        },
    ],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <UserProvider>
                <body className={clsx(`${maax.className} text-primary-dark`)}>
                    {children}
                </body>
            </UserProvider>
        </html>
    );
}
